package de.szut.dqi12.cheftrainer.connectorlib.messagetemplates;

import org.json.JSONObject;

import de.szut.dqi12.cheftrainer.connectorlib.dataexchange.Community;
import de.szut.dqi12.cheftrainer.connectorlib.dataexchange.Manager;
import de.szut.dqi12.cheftrainer.connectorlib.dataexchange.Market;
import de.szut.dqi12.cheftrainer.connectorlib.dataexchange.Player;
import de.szut.dqi12.cheftrainer.connectorlib.messageids.ClientToServer_MessageIDs;
import de.szut.dqi12.cheftrainer.connectorlib.messageids.MIDs;
import de.szut.dqi12.cheftrainer.connectorlib.messages.Message;

/**
 * This Message should be used, when a new {@link Player} should be added to the {@link Market}.
 * @author Alexander Brennecke
 *
 */
public class NewPlayerOnMarketMessage extends Message{
	
	private final static String ID = ClientToServer_MessageIDs.TRANSFER_MARKET;
	private final static String ADD_PLAYER = "addPlayer";
	private Player player;
	private int managerID;
	private int communityID;
	private boolean addPlayer=true;
	
	/**
	 * The Constructor needs a {@link JSONObject}, which has all information to initialize a new object of this class.
	 * In the best case it was generated by the createMessageContent function.
	 * @param json
	 */
	public NewPlayerOnMarketMessage(JSONObject json){
		super(ID);
		managerID = json.getInt(Manager.MANAGER_ID);
		communityID = json.getInt(Community.COMMUNITY_ID);
		addPlayer = json.getBoolean(ADD_PLAYER);
		JSONObject playerJSON= json.getJSONObject(Player.PLAYER);
		player = new Player(playerJSON);
	}
	
	/**
	 * Default Constructor, which can be used, when this class should be defined with setter functions and not with a {@link JSONObject}.
	 */
	public NewPlayerOnMarketMessage(){
		super(ID);
	}
	
	@Override
	public void createMessageContent(){
		JSONObject playerObject = player.toJSON();
		
		JSONObject messageContent = new JSONObject();
		messageContent.put(MIDs.TYPE, MIDs.NEW_MARKET_PLAYER);
		
		messageContent.put(ADD_PLAYER, addPlayer);
		messageContent.put(Manager.MANAGER_ID, managerID);
		messageContent.put(Community.COMMUNITY_ID, communityID);
		messageContent.put(Player.PLAYER, playerObject);
		
		setMessageContent(messageContent);
	}
	
	// GETTER AND SETTER
	
	public Player getPlayer() {
		return player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public int getManagerID() {
		return managerID;
	}

	public void setManagerID(int managerID) {
		this.managerID = managerID;
	}

	public int getCommunityID() {
		return communityID;
	}

	public void setCommunityID(int communityID) {
		this.communityID = communityID;
	}

	public boolean isAddPlayer() {
		return addPlayer;
	}

	public void setAddPlayer(boolean addPlayer) {
		this.addPlayer = addPlayer;
	}
	
	
}
